base16:
  extension: .conf
  output: colors
  supported-systems: [base16]

base24:
  extension: .conf
  output: colors
  supported-systems: [base24]

# Deprecated templates
base16-256-deprecated:
  extension: .conf
  output: colors-256
  supported-systems: [base16]

base24-256-deprecated:
  extension: .conf
  output: colors-256
  supported-systems: [base24]
